version: '3.8'

services:
  db:
    image: postgres:15
    container_name: pg-pratica
    restart: unless-stopped
    environment:
      POSTGRES_DB: posto_combustivel
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d:ro

volumes:
  db-data: {}
